USE [master]
GO

/****** Object:  Database [Interview]    Script Date: 2024/10/9 下午 01:08:32 ******/
CREATE DATABASE [Interview]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Interview', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Interview.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Interview_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Interview_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Interview].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Interview] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Interview] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Interview] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Interview] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Interview] SET ARITHABORT OFF 
GO

ALTER DATABASE [Interview] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Interview] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Interview] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Interview] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Interview] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Interview] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Interview] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Interview] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Interview] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Interview] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Interview] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Interview] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Interview] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Interview] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Interview] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Interview] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Interview] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Interview] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Interview] SET  MULTI_USER 
GO

ALTER DATABASE [Interview] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Interview] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Interview] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Interview] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Interview] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Interview] SET QUERY_STORE = OFF
GO

USE [Interview]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Interview] SET  READ_WRITE 
GO

